# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate New Absolute Turning Angle
#'
#' Function to calculate new absolute turning angle
#' @export
#' @param absta Absolute turning angle
#' @param ta Relative turning angle
#' @return numeric value
getAbsNewC <- function(absta, ta) {
    .Call('_davidoff_getAbsNewC', PACKAGE = 'davidoff', absta, ta)
}

#' Calculate New Endpoints
#'
#' Function to calculate new endpoints
#' @export
#' @param xy \code{matrix} containing xy coordinates
#' @param absta absolute turning angle
#' @param sl step lengths
#' @return numeric value
calcEndpointsC <- function(xy, absta, sl) {
    .Call('_davidoff_calcEndpointsC', PACKAGE = 'davidoff', xy, absta, sl)
}

